version: '3.7'
services: 
  backend: 
    build: ./backend
    restart: always
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    networks:
      - web-net
  
  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/build
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING='true'
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - web-net
  
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - frontend
      - backend
    networks:
      - web-net

networks:
  web-net:
    driver: bridge